### ISSUE TITLE
Unable to receive data about user's current league

### ISSUE THREAD

**Issue by juriadams** [MingweiSamuel/TeemoJS#2]
Hello!

I've discovered this library on the Riot API developer site and really like it so far. 
Still, I'm having some trouble  getting some data, especially about rank information of specific users.

```
api.get('euw1', 'league.getAllLeaguePositionsForSummoner', '95457313')
     .then(data => console.log("[🤖] User has " + data.wins + " wins."));
```

This right here is my code, theoretically, it should be working , but it somehow doesn't want to.
I'm sorry if it's me doing something wrong...

However, I would still appreciate if you could help me with my problem, since I couldn't figure out a fix after about an hour of testing around with my code.

Thank you very much and good job on the library!

Juri A.

**Comment by MingweiSamuel** [comment]
Hey, thanks for stopping by. The `getAllLeaguePositionsForSummoner` method returns an array of LeaguePositionDTOs, one for each Queue type. You'll will need to find the LeaguePosition that matches the queueName you're looking for:

      api.get('euw1', 'league.getAllLeaguePositionsForSummoner', '95457313')
        .then(data => {
          let entry = data.find(e => e.queueType === 'RANKED_SOLO_5x5');
          console.log(entry.wins);
        });

I believe the documentation was wrong yesterday (said it only returned a single LeaguePositionDTO) but seems it has since been fixed. However, the documentation _is_ missing the `queueType` field although it is returned. Also note in the last few days the leagues endpoint for `euw1` has been flaky, but it should be ok now.

**Comment by juriadams** [comment]
Thank you very much! It's working perfectly fine now, just as I wanted it to!
